import { Movie } from '@/types/movie';

export const SAMPLE_MOVIES: Movie[] = [
  {
    id: 1,
    title: 'Spider-Man: Into the Spider-Verse',
    year: 2018,
    genre: ['Animation', 'Action', 'Adventure'],
    language: 'English',
    rating: 8.4,
    plot: 'Teen Miles Morales becomes Spider-Man and must team up with other Spider-heroes to save his dimension.',
    director: 'Bob Persichetti, Peter Ramsey',
    cast: ['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld'],
    mood_tags: ['energetic', 'excited', 'happy', 'adventurous'],
    streaming_platforms: ['Netflix', 'Amazon Prime'],
    trailer_link: 'https://www.youtube.com/watch?v=tg52up16eq0',
    poster: 'https://via.placeholder.com/300x450/FF6B35/FFFFFF?text=Spider-Verse'
  },
  {
    id: 2,
    title: 'Your Name',
    year: 2016,
    genre: ['Animation', 'Romance', 'Drama'],
    language: 'Japanese',
    rating: 8.2,
    plot: 'Two teenagers share a profound, magical connection upon discovering they are swapping bodies.',
    director: 'Makoto Shinkai',
    cast: ['Ryunosuke Kamiki', 'Mone Kamishiraishi'],
    mood_tags: ['romantic', 'nostalgic', 'emotional', 'thoughtful'],
    streaming_platforms: ['Crunchyroll', 'Funimation'],
    trailer_link: 'https://www.youtube.com/watch?v=xU47nhruN-Q',
    poster: 'https://via.placeholder.com/300x450/4A90E2/FFFFFF?text=Your+Name'
  },
  {
    id: 3,
    title: 'Mad Max: Fury Road',
    year: 2015,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    language: 'English',
    rating: 8.1,
    plot: 'In a post-apocalyptic wasteland, Max teams up with Furiosa to escape a tyrannical warlord.',
    director: 'George Miller',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
    mood_tags: ['energetic', 'intense', 'adrenaline', 'rebellious'],
    streaming_platforms: ['HBO Max', 'Amazon Prime'],
    trailer_link: 'https://www.youtube.com/watch?v=hEJnMQG9ev8',
    poster: 'https://via.placeholder.com/300x450/E74C3C/FFFFFF?text=Mad+Max'
  },
  {
    id: 4,
    title: 'The Grand Budapest Hotel',
    year: 2014,
    genre: ['Comedy', 'Adventure', 'Crime'],
    language: 'English',
    rating: 8.1,
    plot: 'The adventures of Gustave H, a concierge at a famous European hotel, and his protégé Zero.',
    director: 'Wes Anderson',
    cast: ['Ralph Fiennes', 'F. Murray Abraham'],
    mood_tags: ['whimsical', 'nostalgic', 'artistic', 'charming'],
    streaming_platforms: ['Amazon Prime', 'Hulu'],
    trailer_link: 'https://www.youtube.com/watch?v=1Fg5iWmQjwk',
    poster: 'https://via.placeholder.com/300x450/F39C12/FFFFFF?text=Grand+Budapest'
  },
  {
    id: 5,
    title: 'Amélie',
    year: 2001,
    genre: ['Comedy', 'Romance'],
    language: 'French',
    rating: 8.3,
    plot: 'A shy waitress decides to help those around her find happiness while discovering love herself.',
    director: 'Jean-Pierre Jeunet',
    cast: ['Audrey Tautou', 'Mathieu Kassovitz'],
    mood_tags: ['whimsical', 'romantic', 'happy', 'charming'],
    streaming_platforms: ['Netflix', 'Amazon Prime'],
    trailer_link: 'https://www.youtube.com/watch?v=He7TaD_V55Y',
    poster: 'https://via.placeholder.com/300x450/7ED321/FFFFFF?text=Amelie'
  },
  {
    id: 6,
    title: 'Moonlight',
    year: 2016,
    genre: ['Drama'],
    language: 'English',
    rating: 7.4,
    plot: 'A chronicle of the childhood, adolescence and burgeoning adulthood of a young, African-American, gay man.',
    director: 'Barry Jenkins',
    cast: ['Mahershala Ali', 'Naomie Harris', 'Trevante Rhodes'],
    mood_tags: ['thoughtful', 'emotional', 'introspective', 'profound'],
    streaming_platforms: ['Netflix', 'Amazon Prime'],
    trailer_link: 'https://www.youtube.com/watch?v=9NJj12tJzqc',
    poster: 'https://via.placeholder.com/300x450/8E44AD/FFFFFF?text=Moonlight'
  },
  {
    id: 7,
    title: 'Klaus',
    year: 2019,
    genre: ['Animation', 'Adventure', 'Comedy'],
    language: 'English',
    rating: 8.2,
    plot: 'A postman stationed in a frozen town forms an unlikely friendship with a local toymaker.',
    director: 'Sergio Pablos',
    cast: ['Jason Schwartzman', 'J.K. Simmons', 'Rashida Jones'],
    mood_tags: ['heartwarming', 'happy', 'family', 'magical'],
    streaming_platforms: ['Netflix'],
    trailer_link: 'https://www.youtube.com/watch?v=taE3UwuAmoc',
    poster: 'https://via.placeholder.com/300x450/50E3C2/FFFFFF?text=Klaus'
  },
  {
    id: 8,
    title: 'Parasite',
    year: 2019,
    genre: ['Thriller', 'Drama', 'Dark Comedy'],
    language: 'Korean',
    rating: 8.5,
    plot: 'A poor family schemes to become employed by a wealthy family by infiltrating their household.',
    director: 'Bong Joon-ho',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    mood_tags: ['intense', 'thought-provoking', 'suspenseful', 'social'],
    streaming_platforms: ['Hulu', 'Amazon Prime'],
    trailer_link: 'https://www.youtube.com/watch?v=5xH0HfJHsaY',
    poster: 'https://via.placeholder.com/300x450/2C3E50/FFFFFF?text=Parasite'
  },
  {
    id: 9,
    title: 'Coco',
    year: 2017,
    genre: ['Animation', 'Adventure', 'Family'],
    language: 'English',
    rating: 8.4,
    plot: 'A young boy enters the Land of the Dead to find his great-great-grandfather, a legendary singer.',
    director: 'Lee Unkrich, Adrian Molina',
    cast: ['Anthony Gonzalez', 'Gael García Bernal'],
    mood_tags: ['emotional', 'family', 'musical', 'colorful'],
    streaming_platforms: ['Disney+', 'Amazon Prime'],
    trailer_link: 'https://www.youtube.com/watch?v=Rvr68u6k5sI',
    poster: 'https://via.placeholder.com/300x450/FF6B35/FFFFFF?text=Coco'
  },
  {
    id: 10,
    title: 'Her',
    year: 2013,
    genre: ['Romance', 'Drama', 'Sci-Fi'],
    language: 'English',
    rating: 8.0,
    plot: 'A lonely writer develops an unlikely relationship with an operating system designed to meet his every need.',
    director: 'Spike Jonze',
    cast: ['Joaquin Phoenix', 'Scarlett Johansson'],
    mood_tags: ['thoughtful', 'romantic', 'melancholic', 'futuristic'],
    streaming_platforms: ['Netflix', 'Amazon Prime'],
    trailer_link: 'https://www.youtube.com/watch?v=WzV6mXIOVl4',
    poster: 'https://via.placeholder.com/300x450/95A5A6/FFFFFF?text=Her'
  },
  {
    id: 11,
    title: 'John Wick',
    year: 2014,
    genre: ['Action', 'Crime', 'Thriller'],
    language: 'English',
    rating: 7.4,
    plot: 'An ex-hit-man comes out of retirement to track down the gangsters that took everything from him.',
    director: 'Chad Stahelski',
    cast: ['Keanu Reeves', 'Michael Nyqvist', 'Alfie Allen'],
    mood_tags: ['angry', 'excited', 'energetic', 'intense'],
    streaming_platforms: ['Amazon Prime', 'Hulu'],
    trailer_link: 'https://www.youtube.com/watch?v=C0BMx-qxsP4',
    poster: 'https://via.placeholder.com/300x450/E74C3C/FFFFFF?text=John+Wick'
  },
  {
    id: 12,
    title: 'La La Land',
    year: 2016,
    genre: ['Romance', 'Comedy', 'Drama', 'Musical'],
    language: 'English',
    rating: 8.0,
    plot: 'While navigating their careers in Los Angeles, a pianist and an actress fall in love.',
    director: 'Damien Chazelle',
    cast: ['Ryan Gosling', 'Emma Stone', 'Rosemarie DeWitt'],
    mood_tags: ['romantic', 'nostalgic', 'happy', 'musical'],
    streaming_platforms: ['Netflix', 'Amazon Prime'],
    trailer_link: 'https://www.youtube.com/watch?v=0pdqf4P9MB8',
    poster: 'https://via.placeholder.com/300x450/E91E63/FFFFFF?text=La+La+Land'
  }
];
